schema:
    - ${NEXT_PUBLIC_CONTENT_GQL_ENDPOINT}/${NEXT_PUBLIC_CONTENT_PUBLIC_KEY}:
          headers
documents: src/**/*.graphql
overwrite: true
verbose: true
generates:
    ${CODEGEN_ROOT_FOLDER_PATH}/content/index.ts:
        hooks:
            afterAllFileWrite:
                - prettier --write
                - eslint --fix
        plugins:
            - typescript
            - typescript-operations
            - typescript-graphql-request
        config:
            gqlImport: graphql-request#gql
            dedupeFragments: true
    schema.graphql:
        plugins:
            - schema-ast
        config:
            includeDirectives: true
            includeIntrospectionTypes: true
